version:     "0002--10-Okt-2022"
copyright:   "2022"
author:      "Raizaz Achmad Asyraf"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/raizazaa/os222/"
myloglink:   "https://raizazaa.github.io/os222/TXT/mylog.txt"
encoding:    "UTF-8"
copyright:   "2022"
github:      [metadata]
